# Gopkg.toml for the Admission Controller webhook demo.
# Copyright (c) 2019 StackRox Inc.

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"

[prune]
  go-tests = true
  unused-packages = true
