apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: demo-webhook
webhooks:
  - name: webhook-server.webhook-demo.svc
    namespaceSelector:
      matchExpressions:
        - key: webhook
          operator: In
          values: ["true"]
    clientConfig:
      url: "https://10.1.11.212:8443/mutate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtVENDQW9HZ0F3SUJBZ0lKQUtYSmVObjkwRXZFTUEwR0NTcUdTSWIzRFFFQkN3VUFNRjh4Q3pBSkJnTlYKQkFZVEFrTk9NUkV3RHdZRFZRUUlEQWhhYUdWS2FXRnVaekVSTUE4R0ExVUVCd3dJU0dGdVoxcG9iM1V4Q3pBSgpCZ05WQkFvTUFraERNUXd3Q2dZRFZRUUxEQU5FWlhZeER6QU5CZ05WQkFNTUJtTmhMbU52YlRBZUZ3MHlNVEEyCk1qZ3dOak01TVROYUZ3MHlNakEyTWpnd05qTTVNVE5hTUY4eEN6QUpCZ05WQkFZVEFrTk9NUkV3RHdZRFZRUUkKREFoYWFHVkthV0Z1WnpFUk1BOEdBMVVFQnd3SVNHRnVaMXBvYjNVeEN6QUpCZ05WQkFvTUFraERNUXd3Q2dZRApWUVFMREFORVpYWXhEekFOQmdOVkJBTU1CbU5oTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFKK1BwbUpkMVZ4bzIyYlJVc1FZUksrSzRRTlpCWktIRHdJNnlWZjhOWXFNTEVKamlDdksKUUM0SXhRR1VaVjIzc0RjUjRJSTZFaUo5RjloejdmUHZBOTE4YnJ4WWVpZG9UUmhjUEd0ZU1MMUNVamNIaDZmego0aTVZNTVhNVY5ZDdtSTV0TE9BQ2w1UHFzTGJ0MjFmanUwSDQyY1plSUdra3JnZmNSNHJzU2E2elZmVGloM21nClRYOCtxL2ROVDNrZ1A4UlZtaXRlSU1DVVdRRXNxOXROSW1HS09WNklKR0dYLzZydTRibEppT0tWS1hmTDArY0gKRzhSTlBtaklTU1czNW5TcHJLT3FRbS9laUhIN2hzaWh5bkd6U0J6RHUxVjkyVi9oaUUyb0JwQ0NCQmRMZzZTagpIVXRuUGREMW1aNlZCNnliYVFmNWEwM0ZuNHE2Si84RzJITUNBd0VBQWFOWU1GWXdEQVlEVlIwVEJBVXdBd0VCCi96QkdCZ05WSFJFRVB6QTlod1RBcURnQmh3Ui9BQUFCaHdRS0FRdlVnZzkzZDNjdVkyOXRjR0Z1ZVM1dVpYU0MKQzJOdmJYQmhibmt1WTI5dGdndGpiMjF3WVc1NUxtNWxkREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBSGt5YgpZa2FIUzBWV1dwNnU0UitlQlVNVkUwNDVzcTNiTnlqbXlYNnovV2pGNDJ0Qk8wbVBNdVN0WjNrUjBYQTMrQUpOCkRRS05ycFBLVWw5WjhkTFM2VW94aTc3Nzd6NGRqQ2ZXTnRwUzRXTDZjUXkvQU9FRkdncTdHS1oxWmR6d3huL1YKWWxidDBRcHBWUHgwcHlMaXo0SXlRNUN2NXkwcVk1YUQ2YnFlaC82ZW9ENXRXbzZPSGx0ZXlSVk1YQ0phc0tpUwpvMUk5d29aQTdtempOdU5GVVgrRTU5QkE3V3Q3U0pNVnIxQVM0bHpMNnA2a2ZRNExrMTBUbkxTMnFLUnZlMjRpCkRGTlp5Z2tqRzJ0MTZibVZwQXViZjFRalp6WlltM2d5R2JvQ1FTTU5sUFJjR0FJWWkrY3Vld1NvaldZeUF2U3MKUDhweEN1NjdLRmxoSDlGYTRBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
    #      service:
#        name: webhook-server
#        namespace: webhook-demo
#        path: "/mutate"
    rules:
      - operations: [ "CREATE","UPDATE"]
#          - operations: [ "CREATE","UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]